version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: invsto-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: invstodb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - db-temp:/var/lib/postgresql/data

volumes:
  db-temp: